spring.application.name=ticketing

# Habilitar los endpoints de salud para el ALB Fargate (Actuator)
management.endpoints.web.exposure.include=health,info

# Por las dudas si DynamoDB intenta auto-conectarse en local sin profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
