# Habilita el log estructurado JSON nativo de Spring Boot 3.4+ para consola
# Esto permite que CloudWatch trate cada log como un objeto JSON y permita queries como { $.level = "ERROR" }
logging.structured.format.console=logstash

# Agregar más metadatos útiles al JSON final para depuración en AWS
logging.level.root=INFO
logging.level.com.example.ticketing=DEBUG
